name: Backend application build and Test
on:
  push:  
    branches:
      - main

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v7
      - name: Build the code
        run: mvn clean install -DskipTests=true
      - name: Test the code
        run: mvn test



    





