name: Backend application build and Test
on:
  workflow_dispatch:  
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v7
      - name: Is code present
        run: ls


    





