name: Backend application build and Test
on:
  push:  
    branches:
      - main

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v7
      - name: install java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
      - name: What version of Java
        run: java --version

     # - name: Build the code
     #   run: mvn clean install -DskipTests=true
     # - name: Test the code
     #   run: mvn test



    





